api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    enable_nelmio_api_doc: true
    exception_to_status:
      App\Exception\NotGrantedFacebookException: 401
doctrine:
    orm:
        filters:
            user_filter:
                class: App\Filter\UserFilter
