nelmio_api_doc:
    documentation:
        info:
            title: Bilemo
            description: This is an Api!
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api/products
            - ^/api/members
            # - ^\/api(?!\/doc|docs$) # Accepts routes under /api except /api/doc
